[package]
name = "mfc-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mango-feeds-connector = "0.2.1"

solana-client = "~1.16.7"
solana-logger = "~1.16.7"
solana-sdk = "~1.16.7"
